name: buid and push to docker hub
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
     - name: Ckeckout-repo
       uses: actions/checkout@V2
     - name: set up java version 17
       uses: actions/setup-java@V2
       with:
         distribution: 'adopt'
         java-version: '17'      
     - name: maven clean package
       run: mvn clean package
       working-directory: javasample
     - name: docker login
       uses: docker/login-actions@V2
       with:
         username: ${{ secret.DOCKER_USERNAME }}
         password: ${{ secret.DOCKER_PASSWORD }} 
     - name: build and push to docker
       uses: docker/build-push-actions@V2
       with:
         context: javasample
         file: javasample/Dockerfile
         push: true
         tags: |
            ${{ secret.DOCKER_USERNAME}}/javaexample:{{ github run_number }}
     - name: logout docker
       run: docker logout


     
